name: ML@GT Blog
description: The lastest news from Research at Georgia Tech
meta_description: "ML@GT Blog: The lastest news from Research at Georgia Tech"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: 
- jekyll-paginate
- jemoji
paginate: 15
domain_name: 'http://mlatgt.blog'
# TODO
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
# TODO
url:            'http://your-blog-url.example.com'
author:         'ML@GT'
authorTwitter:  'mlatgt'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
